from telegramreferralpro.supabase_client import supabase

def create_tables():
    # Create users table
    supabase.rpc("execute_sql", {
        "sql": """
            CREATE TABLE users (
                id bigint generated by default as identity primary key,
                user_id bigint unique not null,
                username text,
                referral_code text unique not null,
                created_at timestamptz default now()
            );
        """
    }).execute()

    # Create referrals table
    supabase.rpc("execute_sql", {
        "sql": """
            CREATE TABLE referrals (
                id bigint generated by default as identity primary key,
                referrer_id bigint references users(id),
                referred_id bigint references users(id),
                created_at timestamptz default now()
            );
        """
    }).execute()

if __name__ == "__main__":
    create_tables()