CREATE TABLE referral_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_level INTEGER NOT NULL DEFAULT 5,
    reward_description TEXT,
    reward_amount DECIMAL(10,2),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add indexes for better performance
CREATE INDEX idx_referral_targets_active ON referral_targets(is_active);
CREATE INDEX idx_referral_targets_level ON referral_targets(target_level);

-- Insert default referral target
INSERT INTO referral_targets (target_level, reward_description, reward_amount) 
VALUES (5, 'Basic referral reward', 10.00);

-- Add a comment to explain the table purpose
COMMENT ON TABLE referral_targets IS 'Stores referral targets and associated rewards for the Telegram bot referral system';